### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (500000,87)

### ISSUE THREAD

**Issue by 24suixinsuoyu** [xiph/rnnoise#158]
I refer to this link: https://blog.csdn.net/dakeboy/article/details/88065399

Under the directory of training, I run the command of "./bin2hdf5.py /Users/suizhongyuan/Desktop/RNNoise/rnnoise/src/output.f32 500000 87 > ./denoise_data9.h5". 
And I got this error as below:

---
suizhongyuan@suizhongyuandeMacBook-Pro training % ./bin2hdf5.py /Users/suizhongyuan/Desktop/RNNoise/rnnoise/src/output.f32 500000 87 > ./denoise_data9.h5
Traceback (most recent call last):
  File "./bin2hdf5.py", line 10, in <module>
    data = np.reshape(data, (int(sys.argv[2]), int(sys.argv[3])));
  File "/Library/Python/2.7/site-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Library/Python/2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 0 into shape (500000,87)
---

I have no idea to handle it. Can I get a clue?

**Comment by 24suixinsuoyu** [comment]
I fixed it by myself. It should run on Python3, and Keras needs TensorFlow 2.2 or higher.

**Comment by 24suixinsuoyu** [comment]
> I refer to this link: https://blog.csdn.net/dakeboy/article/details/88065399
> 
> Under the directory of training, I run the command of "./bin2hdf5.py /Users/suizhongyuan/Desktop/RNNoise/rnnoise/src/output.f32 500000 87 > ./denoise_data9.h5".
> And I got this error as below:
> 
> ## suizhongyuan@suizhongyuandeMacBook-Pro training % ./bin2hdf5.py /Users/suizhongyuan/Desktop/RNNoise/rnnoise/src/output.f32 500000 87 > ./denoise_data9.h5
> Traceback (most recent call last):
> File "./bin2hdf5.py", line 10, in
> data = np.reshape(data, (int(sys.argv[2]), int(sys.argv[3])));
> File "/Library/Python/2.7/site-packages/numpy/core/fromnumeric.py", line 292, in reshape
> return _wrapfunc(a, 'reshape', newshape, order=order)
> File "/Library/Python/2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
> return getattr(obj, method)(*args, **kwds)
> ValueError: cannot reshape array of size 0 into shape (500000,87)
> I have no idea to handle it. Can I get a clue?

I fixed it by myself. It should run on Python3, and Keras needs TensorFlow 2.2 or higher.
