### ISSUE TITLE
dump_rnn error

### ISSUE THREAD

**Issue by carclodefly** [xiph/rnnoise#55]
Dear Sir . when I tried to run dump_rnn.py with my hdf5 data , there is an error occurred,what shoud I do with it ?

Traceback (most recent call last):
  File "./dump_rnn.py", line 60, in <module>
    model = load_model(sys.argv[1], custom_objects={'msse': mean_squared_sqrt_error, 'mean_squared_sqrt_error': mean_squared_sqrt_error, 'my_crossentropy': mean_squared_sqrt_error, 'mycost': mean_squared_sqrt_error, 'WeightClip': foo})
  File "/home/cheyunfei/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/cheyunfei/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 317, in _deserialize_model
    model._make_train_function()
  File "/home/cheyunfei/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "/home/cheyunfei/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/cheyunfei/.conda/envs/tensorflow/lib/python3.6/site-packages/keras/optimizers.py", line 511, in get_updates
    new_p = p.constraint(new_p)
TypeError: 'int' object is not callable

**Comment by xqq2018rebuild** [comment]
I have the same problem, so I can't get the weights which I have trained.

**Comment by carclodefly** [comment]
try again with this
[cyf_dump_rnn.zip](https://github.com/xiph/rnnoise/files/2877954/cyf_dump_rnn.zip)

**Comment by ucasiggcas** [comment]
I have another problem
https://github.com/xiph/rnnoise/issues/85

**Comment by ROAD2018** [comment]
So, what the right dump_rnn.py should be? 
I have the similar problem as: 
          ValueError: Unknown constraint: WeightClip

**Comment by gavingao71** [comment]
modified the code as below:

#def foo(c, name):
#    return 1

#def mean_squared_sqrt_error(y_true, y_pred):
#    return K.mean(K.square(K.sqrt(y_pred) - K.sqrt(y_true)), axis=-1)

def mean_squared_sqrt_error(y_true, y_pred):
    return K.mean(K.square(K.sqrt(y_pred) - K.sqrt(y_true)), axis=-1)

def my_crossentropy(y_true, y_pred):
    return K.mean(2*K.abs(y_true-0.5) * K.binary_crossentropy(y_pred, y_true), axis=-1)

def mymask(y_true):
    return K.minimum(y_true+1., 1.)

def msse(y_true, y_pred):
    return K.mean(mymask(y_true) * K.square(K.sqrt(y_pred) - K.sqrt(y_true)), axis=-1)

def mycost(y_true, y_pred):
    return K.mean(mymask(y_true) * (10*K.square(K.square(K.sqrt(y_pred) - K.sqrt(y_true))) + K.square(K.sqrt(y_pred) - K.sqrt(y_true)) + 0.01*K.binary_crossentropy(y_pred, y_true)), axis=-1)

def my_accuracy(y_true, y_pred):
    return K.mean(2*K.abs(y_true-0.5) * K.equal(y_true, K.round(y_pred)), axis=-1)

class WeightClip(Constraint):
    def __init__(self, c=2,name='WeightClip'):
        self.c = c

        def __call__(self, p):
            #return {'name': self.__class__.__name__, 'c': self.c}
            return K.clip(p, -self.c, self.c)

        def get_config(self):
            return {'name': self.__class__.__name__, 'c': self.c}

model = load_model(sys.argv[1], custom_objects={'msse':msse, 'mean_squared_sqrt_error': mean_squared_sqrt_error, 'my_crossentropy':my_crossentropy, 'mycost':mycost, 'WeightClip':WeightClip})
#model = load_model(sys.argv[1], custom_objects={'msse': mean_squared_sqrt_error, 'mean_squared_sqrt_error': mean_squared_sqrt_error, 'my_crossentropy': mean_squared_sqrt_error, 'mycost': mean_squared_sqrt_error, 'WeightClip': foo})

**Comment by guoyuantao** [comment]
./dump_rnn.py weights.hdf5 ../src/rnn_data.c ../src/rnn_data.h
  File "./dump_rnn.py", line 90
    return K.mean(mymask(y_true) * (10K.square(K.square(K.sqrt(y_pred) - K.sqrt(y_true))) + K.square(K.sqrt(y_pred) - K.sqrt(y_true)) +0.01K.binary_crossentropy(y_pred, y_true)), axis=-1)
                                      ^
SyntaxError: invalid syntax



what should i do to solve the problem

**Comment by 24suixinsuoyu** [comment]
> ./dump_rnn.py weights.hdf5 ../src/rnn_data.c ../src/rnn_data.h
> File "./dump_rnn.py", line 90
> return K.mean(mymask(y_true) * (10K.square(K.square(K.sqrt(y_pred) - K.sqrt(y_true))) + K.square(K.sqrt(y_pred) - K.sqrt(y_true)) +0.01K.binary_crossentropy(y_pred, y_true)), axis=-1)
> ^
> SyntaxError: invalid syntax
> 
> what should i do to solve the problem

I have met the same problem.

**Comment by 24suixinsuoyu** [comment]
> ./dump_rnn.py weights.hdf5 ../src/rnn_data.c ../src/rnn_data.h
> File "./dump_rnn.py", line 90
> return K.mean(mymask(y_true) * (10K.square(K.square(K.sqrt(y_pred) - K.sqrt(y_true))) + K.square(K.sqrt(y_pred) - K.sqrt(y_true)) +0.01K.binary_crossentropy(y_pred, y_true)), axis=-1)
> ^
> SyntaxError: invalid syntax
> 
> what should i do to solve the problem

It missed two multiple signs(asterisk), do like this:

10 * K        0.01 * K

**Comment by 24suixinsuoyu** [comment]
> So, what the right dump_rnn.py should be?
> I have the similar problem as:
> ValueError: Unknown constraint: WeightClip

I fixed it, try this:

class WeightClip(Constraint):
        def __init__(self, c=2, name='WeightClip'):
                self.c=c
